apiVersion: v1
kind: ConfigMap
metadata:
  name: service-configs
data:
  INVENTORY_EP: "http://inventory-svc:8080"
  PAYMENTS_EP: "http://payments-svc:8080"
  ACTIVE_ITEM_TYPE: "burgers"
  ITEMS: |
    items:
      - name: "BigBurger"
        type: "burgers"
        price: 6.50
        imageUrl: "usr/lib/images/bigburger.png"
        quantity: 200
        labels: [ "retail", "restaurant", "food" ]
      - name: "DoubleBurger"
        type: "burgers"
        price: 9.25
        imageUrl: "usr/lib/images/burgers.png"
        quantity: 200
        labels: [ "retail", "restaurant", "food" ]
      - name: "Shirt"
        type: "textile"
        price: 15.50
        imageUrl: "usr/lib/images/shirt.png"
        quantity: 50
        labels: [ "retail", "textile", "clothing" ]
      - name: "Short"
        type: "textile"
        price: 17.20
        imageUrl: "usr/lib/images/short.png"
        quantity: 20
        labels: [ "retail", "textile", "clothing" ]
