apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-profile
data:
  SPRING_PROFILES_ACTIVE: "INMEMORY"

---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: spring-profile
# data:
#   SPRING_PROFILES_ACTIVE: "DATABASE"
